language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpunit -c ./tests/phpunit.xml
  - phpunit -c ./tests/phpunit-multisite.xml

after_script:
  - php vendor/bin/codacycoverage clover path/to/clover.xml
